collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.07526882
color:
  saturation: 0
  brandStrength: 0.004017804
  lightness: 0
  rhythmicContrast: 0
layout_spectrum: 0
name: The Avenue Art
