layout_spectrum: 0.9462366
color:
  saturation: 0.768993
  brandStrength: 0.004017804
  lightness: 0.1577061
  rhythmicContrast: 0.4614142
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
typography_spectrum: 0.09677419
name: The Avenue Art
