collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.07526882
color:
  saturation: 1
  lightness: 1
  brandStrength: 0.004017804
  rhythmicContrast: 1
layout_spectrum: 0.6541219
name: The Avenue Art
